risk:
  coefficients:
    - riskType: "FIRE"
      normal: "0.014"
      modified: "0.024"
      threshold: "100.0"
      condition: "GREATER"
    - riskType: "THEFT"
      normal: "0.11"
      modified: "0.05"
      threshold: "15.0"
      condition: "GREATER_OR_EQUAL"